version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./temp:/app/temp
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - ENABLE_OPENCASCADE=true
    restart: unless-stopped
    
  # Optional: Redis for async processing
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped