name: Docker Build Fast (AMD64 only)

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - feature/*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push (fast mode)
        run: |
          # Simple docker build without buildx for speed
          IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          
          echo "Building image: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .
          
          echo "Pushing image..."
          docker push $IMAGE_TAG
          
          # Also tag as branch name
          BRANCH_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_REF##*/}"
          docker tag $IMAGE_TAG $BRANCH_TAG
          docker push $BRANCH_TAG
          
          echo "## 🚀 Fast Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "Image: \`$IMAGE_TAG\`" >> $GITHUB_STEP_SUMMARY
          echo "Branch: \`$BRANCH_TAG\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Pull: \`docker pull $IMAGE_TAG\`" >> $GITHUB_STEP_SUMMARY